/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import dioramaGlb from './assets/diorama.glb'

const Diorama = (props) => {
  const group = useRef()
  const { nodes, materials } = useGLTF(dioramaGlb)

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.68, 1.03, 0.03]} rotation={[0, 0.24, 0]} scale={[1.37, 1.37, 1.37]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_1.geometry}
          material={nodes.Circle_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_2.geometry}
          material={nodes.Circle_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_3.geometry}
          material={nodes.Circle_3.material}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={nodes.Plane_1.material}
          position={[0.86, 0.58, 0.23]}
          rotation={[1.58, 0.18, -1.64]}
          scale={[0.32, 0.32, 0.32]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={nodes.Plane003_1.material}
          position={[0.88, 0.46, 0.16]}
          rotation={[-1.56, -0.22, -1.58]}
          scale={[0.24, 0.24, 0.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={nodes.Plane004.material}
          position={[0.86, 0.56, 0.03]}
          rotation={[1.58, 0.22, -1.56]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={nodes.Plane005_1.material}
          position={[0.76, 1.04, -0.21]}
          rotation={[-1.56, -0.22, -1.58]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={nodes.Plane006_1.material}
          position={[0.68, 1.04, -0.38]}
          rotation={[1.7, 0.19, -2.36]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={nodes.Plane007.material}
          position={[0.91, 0.36, 0.04]}
          rotation={[-1.56, -0.22, -1.58]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={nodes.Plane008.material}
          position={[0.66, 1.04, 0.41]}
          rotation={[1.43, 0.18, -0.77]}
          scale={[0.26, 0.26, 0.26]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={nodes.Plane009.material}
          position={[0.42, 1.01, 0.66]}
          rotation={[1.41, 0.19, -0.77]}
          scale={[0.18, 0.18, 0.18]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={nodes.Plane010.material}
          position={[0.39, 0.94, 0.72]}
          rotation={[1.41, 0.14, -0.62]}
          scale={[0.13, 0.13, 0.13]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={nodes.Plane011.material}
          position={[0.08, 0.6, 0.86]}
          rotation={[-1.79, 0.01, 3.13]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={nodes.Plane012.material}
          position={[-0.01, 0.49, 0.88]}
          rotation={[1.35, 0.01, 0.01]}
          scale={[0.24, 0.24, 0.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={nodes.Plane013.material}
          position={[-0.12, 0.39, 0.9]}
          rotation={[-1.79, 0.01, 3.13]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={nodes.Plane014.material}
          position={[0.06, 0.4, 0.9]}
          rotation={[-1.79, 0.01, 3.13]}
          scale={[0.22, 0.22, 0.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={nodes.Plane015.material}
          position={[0.04, 1.03, 0.76]}
          rotation={[-1.79, 0.01, 3.13]}
          scale={[0.24, 0.24, 0.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016.geometry}
          material={nodes.Plane016.material}
          position={[0.21, 1.03, 0.76]}
          rotation={[1.35, 0, 0.01]}
          scale={[0.19, 0.19, 0.19]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017.geometry}
          material={nodes.Plane017.material}
          position={[0.23, 0.95, 0.78]}
          rotation={[-1.79, 0.01, 3.13]}
          scale={[0.15, 0.15, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018.geometry}
          material={nodes.Plane018.material}
          position={[-0.68, 0.47, 0.56]}
          rotation={[1.4, -0.14, 0.76]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={nodes.Plane019.material}
          position={[-0.76, 0.37, 0.51]}
          rotation={[-1.73, 0.15, 2.38]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020.geometry}
          material={nodes.Plane020.material}
          position={[-0.6, 0.38, 0.67]}
          rotation={[-1.73, 0.15, 2.38]}
          scale={[0.22, 0.22, 0.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021.geometry}
          material={nodes.Plane021.material}
          position={[-0.61, 0.58, 0.6]}
          rotation={[-1.73, 0.15, 2.38]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022.geometry}
          material={nodes.Plane022.material}
          position={[-0.47, 0.99, 0.61]}
          rotation={[-1.72, 0.14, 2.36]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane023.geometry}
          material={nodes.Plane023.material}
          position={[-0.58, 0.88, 0.54]}
          rotation={[-1.74, 0.15, 2.37]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024.geometry}
          material={nodes.Plane024.material}
          position={[-0.42, 0.89, 0.69]}
          rotation={[-1.74, 0.15, 2.37]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane025.geometry}
          material={nodes.Plane025.material}
          position={[-0.86, 0.49, -0.12]}
          rotation={[-1.55, 0.2, 1.54]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026.geometry}
          material={nodes.Plane026.material}
          position={[-0.9, 0.39, -0.12]}
          rotation={[-1.56, 0.3, 1.55]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane027.geometry}
          material={nodes.Plane027.material}
          position={[-0.88, 0.44, 0.07]}
          rotation={[-1.56, 0.3, 1.55]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028.geometry}
          material={nodes.Plane028.material}
          position={[-0.77, 0.99, -0.11]}
          rotation={[-1.55, 0.2, 1.54]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029.geometry}
          material={nodes.Plane029.material}
          position={[-0.79, 0.87, -0.03]}
          rotation={[-1.55, 0.2, 1.54]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane030.geometry}
          material={nodes.Plane030.material}
          position={[-0.82, 0.76, 0.06]}
          rotation={[-1.55, 0.2, 1.54]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031.geometry}
          material={nodes.Plane031.material}
          position={[-0.42, 1, -0.65]}
          rotation={[-1.36, 0.18, 0.81]}
          scale={[0.26, 0.26, 0.26]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032.geometry}
          material={nodes.Plane032.material}
          position={[-0.5, 0.89, -0.62]}
          rotation={[-1.36, 0.18, 0.81]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane033.geometry}
          material={nodes.Plane033.material}
          position={[-0.56, 0.99, -0.52]}
          rotation={[-1.48, 0.12, 0.77]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034.geometry}
          material={nodes.Plane034.material}
          position={[-0.47, 0.46, -0.79]}
          rotation={[-1.41, 0.12, 0.79]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035.geometry}
          material={nodes.Plane035.material}
          position={[-0.55, 0.36, -0.73]}
          rotation={[-1.41, 0.12, 0.79]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane036.geometry}
          material={nodes.Plane036.material}
          position={[-0.58, 0.54, -0.64]}
          rotation={[-1.41, 0.12, 0.79]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane037.geometry}
          material={nodes.Plane037.material}
          position={[-0.69, 0.44, -0.56]}
          rotation={[-1.41, 0.12, 0.79]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane038.geometry}
          material={nodes.Plane038.material}
          position={[0.19, 0.99, -0.76]}
          rotation={[-1.48, 0, -0.07]}
          scale={[0.26, 0.26, 0.26]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane039.geometry}
          material={nodes.Plane039.material}
          position={[0.1, 0.88, -0.77]}
          rotation={[-1.48, 0, -0.07]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane040.geometry}
          material={nodes.Plane040.material}
          position={[-0.08, 0.97, -0.78]}
          rotation={[-1.48, -0.01, -0.07]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041.geometry}
          material={nodes.Plane041.material}
          position={[-0.18, 0.47, -0.88]}
          rotation={[-1.31, -0.01, -0.01]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane042.geometry}
          material={nodes.Plane042.material}
          position={[0.01, 0.42, -0.89]}
          rotation={[1.83, -0.02, -3.13]}
          scale={[0.22, 0.22, 0.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane043.geometry}
          material={nodes.Plane043.material}
          position={[0.18, 0.36, -0.9]}
          rotation={[-1.31, -0.01, -0.01]}
          scale={[0.26, 0.26, 0.26]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane044.geometry}
          material={nodes.Plane044.material}
          position={[0.58, 0.93, -0.48]}
          rotation={[1.64, 0.13, -2.41]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane045.geometry}
          material={nodes.Plane045.material}
          position={[0.51, 1.04, -0.54]}
          rotation={[1.56, 0.05, -2.35]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane046.geometry}
          material={nodes.Plane046.material}
          position={[0.62, 0.44, -0.56]}
          rotation={[1.81, 0.29, -2.45]}
          scale={[0.32, 0.32, 0.32]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane047.geometry}
          material={nodes.Plane047.material}
          position={[0.56, 0.35, -0.68]}
          rotation={[2.14, 0.53, -2.5]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane048.geometry}
          material={nodes.Plane048.material}
          position={[0.45, 0.43, -0.73]}
          rotation={[1.69, 0.18, -2.41]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane049.geometry}
          material={nodes.Plane049.material}
          position={[0.52, 0.54, -0.63]}
          rotation={[1.69, 0.18, -2.41]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={nodes.Circle003.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004.geometry}
          material={nodes.Circle004.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005.geometry}
          material={nodes.Circle005.material}
          position={[0, 0.01, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006.geometry}
          material={nodes.Circle006.material}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_1.geometry}
            material={nodes.Circle002_1.material}
            scale={[1.01, 1.01, 1.01]}
          />
        </mesh>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Ground}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[-0.34, 1.21, -1.54]}
        scale={[0.25, 0.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof.geometry}
        material={materials.RoofTile}
        position={[-0.43, 1.74, 0.11]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.06, 0.09, 0.09]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere002.geometry}
        material={materials.Rock}
        position={[1.82, 0.68, 2.29]}
        rotation={[0.48, 0.4, -0.25]}
        scale={[0.72, 1.12, 1.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
        position={[0.96, 0.87, 2.62]}
        scale={[0.54, 0.54, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere003.geometry}
        material={nodes.Icosphere003.material}
        position={[-0.93, 0.87, 1.56]}
        rotation={[1.21, 0.74, 2.95]}
        scale={[0.54, 0.54, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere004.geometry}
        material={nodes.Icosphere004.material}
        position={[-1.4, 1.03, 1.34]}
        scale={[0.54, 0.54, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere005.geometry}
        material={nodes.Icosphere005.material}
        position={[0.97, 1, -0.37]}
        scale={[0.54, 0.54, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere006.geometry}
        material={nodes.Icosphere006.material}
        position={[3.13, 0.35, -3.13]}
        rotation={[0.26, -0.33, 0.91]}
        scale={[0.64, 0.64, 0.64]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001.geometry}
        material={nodes.Icosphere001.material}
        position={[3.28, 0.21, -2.69]}
        rotation={[1.55, -0.27, -2.88]}
        scale={[0.64, 0.64, 0.64]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere007.geometry}
        material={nodes.Icosphere007.material}
        position={[3.62, 0.21, -2.98]}
        rotation={[1.78, -0.03, 3.11]}
        scale={[0.64, 0.64, 0.64]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere008.geometry}
        material={nodes.Icosphere008.material}
        position={[-2.09, 0.9, 2.93]}
        rotation={[2.51, -0.95, -3.09]}
        scale={[0.74, 0.74, 0.74]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere009.geometry}
        material={nodes.Icosphere009.material}
        position={[1.98, 0.75, 3.35]}
        rotation={[0, 1.43, 0]}
        scale={[0.54, 0.54, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere010.geometry}
        material={nodes.Icosphere010.material}
        position={[2.45, 0.62, 3.16]}
        rotation={[0, 1.43, 0]}
        scale={[0.54, 0.54, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere011.geometry}
        material={nodes.Icosphere011.material}
        position={[-0.48, 0.87, 1.29]}
        rotation={[1.21, 0.74, 2.95]}
        scale={[0.54, 0.54, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere012.geometry}
        material={nodes.Icosphere012.material}
        position={[-3.25, 0.9, 1.96]}
        rotation={[2.51, -0.95, -3.09]}
        scale={[0.74, 0.74, 0.74]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere013.geometry}
        material={nodes.Icosphere013.material}
        position={[-3.41, 1.04, 0.72]}
        rotation={[-0.03, 0.08, -0.29]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere014.geometry}
        material={nodes.Icosphere014.material}
        position={[-3.43, 0.99, 0.44]}
        rotation={[-0.03, 0.08, -0.29]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere015.geometry}
        material={nodes.Icosphere015.material}
        position={[-3.53, 0.95, -0.01]}
        rotation={[-2.38, 1.03, -2.47]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere016.geometry}
        material={nodes.Icosphere016.material}
        position={[-3.48, 0.92, -0.53]}
        rotation={[-0.03, 0.08, -0.29]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere017.geometry}
        material={nodes.Icosphere017.material}
        position={[-3.44, 0.87, -0.92]}
        rotation={[-2.53, 1.28, -2.5]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere018.geometry}
        material={nodes.Icosphere018.material}
        position={[-2.42, 1, 0.76]}
        rotation={[-2.38, 1.03, -2.47]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere019.geometry}
        material={nodes.Icosphere019.material}
        position={[-2.15, 1, 0.96]}
        rotation={[-2.38, 1.03, -2.47]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere020.geometry}
        material={nodes.Icosphere020.material}
        position={[-1.57, 0.99, 3.12]}
        rotation={[-0.03, 0.08, -0.29]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere021.geometry}
        material={nodes.Icosphere021.material}
        position={[-1.53, 0.8, 2.9]}
        rotation={[1.4, 0.37, -0.65]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere022.geometry}
        material={nodes.Icosphere022.material}
        position={[1.45, 0.65, 3.18]}
        rotation={[-0.03, 0.08, -0.29]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere023.geometry}
        material={nodes.Icosphere023.material}
        position={[1.81, 0.9, -0.66]}
        rotation={[-1.39, 0.49, -2.1]}
        scale={[0.36, 0.36, 0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere024.geometry}
        material={nodes.Icosphere024.material}
        position={[1.46, 0.96, -0.45]}
        rotation={[-0.03, 0.08, -0.29]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere025.geometry}
        material={nodes.Icosphere025.material}
        position={[2.05, 0.95, -1.11]}
        rotation={[0.4, 0.8, 0.54]}
        scale={[0.46, 0.46, 0.46]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere026.geometry}
        material={nodes.Icosphere026.material}
        position={[1.54, 0.98, -2.59]}
        rotation={[-1.39, 0.49, -2.1]}
        scale={[0.36, 0.36, 0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere027.geometry}
        material={nodes.Icosphere027.material}
        position={[1.83, 0.96, -2.26]}
        rotation={[-1.07, 0.12, -3.07]}
        scale={[0.36, 0.36, 0.36]}
      />
      <group
        position={[-3.15, 2.07, 3.21]}
        rotation={[-Math.PI, 0.67, -Math.PI]}
        scale={[0.8, 0.58, 0.83]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008.geometry}
          material={nodes.Circle008.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_1.geometry}
          material={nodes.Circle008_1.material}
        />
      </group>
      <group
        position={[-1.89, 1.79, 3.53]}
        rotation={[-Math.PI, -0.46, -Math.PI]}
        scale={[0.51, 0.37, 0.53]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_2.geometry}
          material={nodes.Circle008_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_3.geometry}
          material={nodes.Circle008_3.material}
        />
      </group>
      <group position={[-3.39, 1.88, 2.21]} rotation={[0, 0.63, 0]} scale={[0.57, 0.41, 0.59]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_4.geometry}
          material={nodes.Circle008_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_5.geometry}
          material={nodes.Circle008_5.material}
        />
      </group>
      <group
        position={[-2.14, 2.13, -1.49]}
        rotation={[-Math.PI, -0.48, -Math.PI]}
        scale={[1.07, 0.78, 1.12]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_6.geometry}
          material={nodes.Circle008_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_7.geometry}
          material={nodes.Circle008_7.material}
        />
      </group>
      <group
        position={[-2.06, 2.01, -2.84]}
        rotation={[-Math.PI, 0.34, -Math.PI]}
        scale={[0.91, 0.66, 0.95]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_8.geometry}
          material={nodes.Circle008_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_9.geometry}
          material={nodes.Circle008_9.material}
        />
      </group>
      <group position={[-0.65, 1.91, -2.83]} rotation={[0, 1.31, 0]} scale={[1.06, 0.77, 1.11]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_10.geometry}
          material={nodes.Circle008_10.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_11.geometry}
          material={nodes.Circle008_11.material}
        />
      </group>
      <group
        position={[-1.54, 1.61, -3.57]}
        rotation={[-Math.PI, -0.55, -Math.PI]}
        scale={[0.58, 0.43, 0.61]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_12.geometry}
          material={nodes.Circle008_12.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_13.geometry}
          material={nodes.Circle008_13.material}
        />
      </group>
      <group position={[0.65, 1.61, -3.36]} rotation={[0, 1.24, 0]} scale={[0.85, 0.62, 0.89]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_14.geometry}
          material={nodes.Circle008_14.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_15.geometry}
          material={nodes.Circle008_15.material}
        />
      </group>
      <group
        position={[1.5, 1.21, -3.17]}
        rotation={[-Math.PI, 0.25, -Math.PI]}
        scale={[0.51, 0.37, 0.53]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_16.geometry}
          material={nodes.Circle008_16.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_17.geometry}
          material={nodes.Circle008_17.material}
        />
      </group>
      <group position={[2.4, 1.38, -3.44]} rotation={[0, 0.51, 0]} scale={[0.89, 0.65, 0.93]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_18.geometry}
          material={nodes.Circle008_18.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_19.geometry}
          material={nodes.Circle008_19.material}
        />
      </group>
      <group
        position={[-2.39, 1.51, 0.01]}
        rotation={[-Math.PI, 0.79, -Math.PI]}
        scale={[0.47, 0.34, 0.49]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_20.geometry}
          material={nodes.Circle008_20.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_21.geometry}
          material={nodes.Circle008_21.material}
        />
      </group>
      <group
        position={[-2.81, 1.59, -3.64]}
        rotation={[-Math.PI, -0.55, -Math.PI]}
        scale={[0.49, 0.36, 0.51]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_22.geometry}
          material={nodes.Circle008_22.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_23.geometry}
          material={nodes.Circle008_23.material}
        />
      </group>
      <group position={[1.01, 1, -1.58]} rotation={[0, 0.89, 0]} scale={[1.12, 1.12, 1.12]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010.geometry}
          material={nodes.Circle010.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010_1.geometry}
          material={nodes.Circle010_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010_2.geometry}
          material={nodes.Circle010_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle024.geometry}
          material={nodes.Circle024.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle026.geometry}
          material={nodes.Circle026.material}
          position={[0, 0.01, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle027.geometry}
          material={nodes.Circle027.material}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle023.geometry}
            material={nodes.Circle023.material}
            scale={[1.01, 1.01, 1.01]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane050.geometry}
          material={nodes.Plane050.material}
          position={[0.86, 0.58, 0.23]}
          rotation={[1.58, 0.18, -1.64]}
          scale={[0.32, 0.32, 0.32]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane051.geometry}
          material={nodes.Plane051.material}
          position={[0.88, 0.46, 0.16]}
          rotation={[-1.56, -0.22, -1.58]}
          scale={[0.24, 0.24, 0.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane052.geometry}
          material={nodes.Plane052.material}
          position={[0.86, 0.56, 0.03]}
          rotation={[1.58, 0.22, -1.56]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane053.geometry}
          material={nodes.Plane053.material}
          position={[0.76, 1.04, -0.21]}
          rotation={[-1.56, -0.22, -1.58]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane054.geometry}
          material={nodes.Plane054.material}
          position={[0.68, 1.04, -0.38]}
          rotation={[1.7, 0.19, -2.36]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane055.geometry}
          material={nodes.Plane055.material}
          position={[0.91, 0.36, 0.04]}
          rotation={[-1.56, -0.22, -1.58]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane056.geometry}
          material={nodes.Plane056.material}
          position={[0.66, 1.04, 0.41]}
          rotation={[1.43, 0.18, -0.77]}
          scale={[0.26, 0.26, 0.26]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane057.geometry}
          material={nodes.Plane057.material}
          position={[0.42, 1.01, 0.66]}
          rotation={[1.41, 0.19, -0.77]}
          scale={[0.18, 0.18, 0.18]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane058.geometry}
          material={nodes.Plane058.material}
          position={[0.39, 0.94, 0.72]}
          rotation={[1.41, 0.14, -0.62]}
          scale={[0.13, 0.13, 0.13]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane059.geometry}
          material={nodes.Plane059.material}
          position={[0.08, 0.6, 0.86]}
          rotation={[-1.79, 0.01, 3.13]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane060.geometry}
          material={nodes.Plane060.material}
          position={[-0.01, 0.49, 0.88]}
          rotation={[1.35, 0.01, 0.01]}
          scale={[0.24, 0.24, 0.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane061.geometry}
          material={nodes.Plane061.material}
          position={[-0.12, 0.39, 0.9]}
          rotation={[-1.79, 0.01, 3.13]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane062.geometry}
          material={nodes.Plane062.material}
          position={[0.06, 0.4, 0.9]}
          rotation={[-1.79, 0.01, 3.13]}
          scale={[0.22, 0.22, 0.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane063.geometry}
          material={nodes.Plane063.material}
          position={[0.04, 1.03, 0.76]}
          rotation={[-1.79, 0.01, 3.13]}
          scale={[0.24, 0.24, 0.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane064.geometry}
          material={nodes.Plane064.material}
          position={[0.21, 1.03, 0.76]}
          rotation={[1.35, 0, 0.01]}
          scale={[0.19, 0.19, 0.19]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane065.geometry}
          material={nodes.Plane065.material}
          position={[0.23, 0.95, 0.78]}
          rotation={[-1.79, 0.01, 3.13]}
          scale={[0.15, 0.15, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane066.geometry}
          material={nodes.Plane066.material}
          position={[-0.68, 0.47, 0.56]}
          rotation={[1.4, -0.14, 0.76]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067.geometry}
          material={nodes.Plane067.material}
          position={[-0.76, 0.37, 0.51]}
          rotation={[-1.73, 0.15, 2.38]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane068.geometry}
          material={nodes.Plane068.material}
          position={[-0.6, 0.38, 0.67]}
          rotation={[-1.73, 0.15, 2.38]}
          scale={[0.22, 0.22, 0.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane069.geometry}
          material={nodes.Plane069.material}
          position={[-0.61, 0.58, 0.6]}
          rotation={[-1.73, 0.15, 2.38]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane070.geometry}
          material={nodes.Plane070.material}
          position={[-0.47, 0.99, 0.61]}
          rotation={[-1.72, 0.14, 2.36]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane071.geometry}
          material={nodes.Plane071.material}
          position={[-0.58, 0.88, 0.54]}
          rotation={[-1.74, 0.15, 2.37]}
          scale={[0.31, 0.31, 0.31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane072.geometry}
          material={nodes.Plane072.material}
          position={[-0.42, 0.89, 0.69]}
          rotation={[-1.74, 0.15, 2.37]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane073.geometry}
          material={nodes.Plane073.material}
          position={[-0.86, 0.49, -0.12]}
          rotation={[-1.55, 0.2, 1.54]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane074.geometry}
          material={nodes.Plane074.material}
          position={[-0.9, 0.39, -0.12]}
          rotation={[-1.56, 0.3, 1.55]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane075.geometry}
          material={nodes.Plane075.material}
          position={[-0.88, 0.44, 0.07]}
          rotation={[-1.56, 0.3, 1.55]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane076.geometry}
          material={nodes.Plane076.material}
          position={[-0.77, 0.99, -0.11]}
          rotation={[-1.55, 0.2, 1.54]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane077.geometry}
          material={nodes.Plane077.material}
          position={[-0.79, 0.87, -0.03]}
          rotation={[-1.55, 0.2, 1.54]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane078.geometry}
          material={nodes.Plane078.material}
          position={[-0.82, 0.76, 0.06]}
          rotation={[-1.55, 0.2, 1.54]}
          scale={[0.29, 0.29, 0.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane079.geometry}
          material={nodes.Plane079.material}
          position={[-0.42, 1, -0.65]}
          rotation={[-1.36, 0.18, 0.81]}
          scale={[0.26, 0.26, 0.26]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane080.geometry}
          material={nodes.Plane080.material}
          position={[-0.5, 0.89, -0.62]}
          rotation={[-1.36, 0.18, 0.81]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane081.geometry}
          material={nodes.Plane081.material}
          position={[-0.56, 0.99, -0.52]}
          rotation={[-1.48, 0.12, 0.77]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane082.geometry}
          material={nodes.Plane082.material}
          position={[-0.47, 0.46, -0.79]}
          rotation={[-1.41, 0.12, 0.79]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane083.geometry}
          material={nodes.Plane083.material}
          position={[-0.55, 0.36, -0.73]}
          rotation={[-1.41, 0.12, 0.79]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane084.geometry}
          material={nodes.Plane084.material}
          position={[-0.58, 0.54, -0.64]}
          rotation={[-1.41, 0.12, 0.79]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane085.geometry}
          material={nodes.Plane085.material}
          position={[-0.69, 0.44, -0.56]}
          rotation={[-1.41, 0.12, 0.79]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane086.geometry}
          material={nodes.Plane086.material}
          position={[0.19, 0.99, -0.76]}
          rotation={[-1.48, 0, -0.07]}
          scale={[0.26, 0.26, 0.26]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane087.geometry}
          material={nodes.Plane087.material}
          position={[0.1, 0.88, -0.77]}
          rotation={[-1.48, 0, -0.07]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane088.geometry}
          material={nodes.Plane088.material}
          position={[-0.08, 0.97, -0.78]}
          rotation={[-1.48, -0.01, -0.07]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane089.geometry}
          material={nodes.Plane089.material}
          position={[-0.18, 0.47, -0.88]}
          rotation={[-1.31, -0.01, -0.01]}
          scale={[0.28, 0.28, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane090.geometry}
          material={nodes.Plane090.material}
          position={[0.01, 0.42, -0.89]}
          rotation={[1.83, -0.02, -3.13]}
          scale={[0.22, 0.22, 0.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane091.geometry}
          material={nodes.Plane091.material}
          position={[0.18, 0.36, -0.9]}
          rotation={[-1.31, -0.01, -0.01]}
          scale={[0.26, 0.26, 0.26]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane092.geometry}
          material={nodes.Plane092.material}
          position={[0.58, 0.93, -0.48]}
          rotation={[1.64, 0.13, -2.41]}
          scale={[0.27, 0.27, 0.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane093.geometry}
          material={nodes.Plane093.material}
          position={[0.51, 1.04, -0.54]}
          rotation={[1.56, 0.05, -2.35]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane094.geometry}
          material={nodes.Plane094.material}
          position={[0.62, 0.44, -0.56]}
          rotation={[1.81, 0.29, -2.45]}
          scale={[0.32, 0.32, 0.32]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane095.geometry}
          material={nodes.Plane095.material}
          position={[0.56, 0.35, -0.68]}
          rotation={[2.14, 0.53, -2.5]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane096.geometry}
          material={nodes.Plane096.material}
          position={[0.45, 0.43, -0.73]}
          rotation={[1.69, 0.18, -2.41]}
          scale={[0.25, 0.25, 0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane097.geometry}
          material={nodes.Plane097.material}
          position={[0.52, 0.54, -0.63]}
          rotation={[1.69, 0.18, -2.41]}
          scale={[0.25, 0.25, 0.25]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane098.geometry}
        material={nodes.Plane098.material}
        position={[-0.32, 2.78, -1.25]}
        rotation={[1.58, 0.03, -0.04]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane099.geometry}
        material={nodes.Plane099.material}
        position={[-0.4, 2.66, -1.25]}
        rotation={[1.58, 0.03, -0.04]}
        scale={[0.29, 0.29, 0.29]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane100.geometry}
        material={nodes.Plane100.material}
        position={[-0.18, 2.66, -1.26]}
        rotation={[1.58, 0.03, -0.04]}
        scale={[0.29, 0.29, 0.29]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane101.geometry}
        material={nodes.Plane101.material}
        position={[-0.24, 2.53, -1.26]}
        rotation={[1.58, 0.03, -0.04]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane102.geometry}
        material={nodes.Plane102.material}
        position={[-0.41, 2.27, -1.25]}
        rotation={[1.58, 0.03, -0.03]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane103.geometry}
        material={nodes.Plane103.material}
        position={[-0.3, 2.15, -1.26]}
        rotation={[1.58, 0.03, -0.03]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane104.geometry}
        material={nodes.Plane104.material}
        position={[-0.39, 2.02, -1.26]}
        rotation={[1.58, 0.03, -0.03]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane105.geometry}
        material={nodes.Plane105.material}
        position={[-0.32, 1.65, -1.26]}
        rotation={[1.59, 0.03, 0]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane106.geometry}
        material={nodes.Plane106.material}
        position={[-0.24, 1.51, -1.26]}
        rotation={[1.59, 0.03, 0]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane107.geometry}
        material={nodes.Plane107.material}
        position={[-0.04, 2.35, -1.4]}
        rotation={[1.58, -0.03, -1.61]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane108.geometry}
        material={nodes.Plane108.material}
        position={[-0.05, 2.22, -1.49]}
        rotation={[1.58, -0.02, -1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane109.geometry}
        material={nodes.Plane109.material}
        position={[-0.05, 2.35, -1.63]}
        rotation={[1.58, 0.01, -1.67]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane110.geometry}
        material={nodes.Plane110.material}
        position={[-0.04, 2.48, -1.52]}
        rotation={[1.58, -0.03, -1.61]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane111.geometry}
        material={nodes.Plane111.material}
        position={[-0.05, 2.61, -1.61]}
        rotation={[1.58, 0, -1.67]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane112.geometry}
        material={nodes.Plane112.material}
        position={[-0.06, 2.73, -1.7]}
        rotation={[1.58, 0, -1.67]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane113.geometry}
        material={nodes.Plane113.material}
        position={[-0.04, 2.72, -1.47]}
        rotation={[1.58, -0.01, -1.61]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane114.geometry}
        material={nodes.Plane114.material}
        position={[-0.06, 1.69, -1.65]}
        rotation={[1.58, -0.02, -1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane115.geometry}
        material={nodes.Plane115.material}
        position={[-0.06, 1.56, -1.56]}
        rotation={[1.58, -0.02, -1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane116.geometry}
        material={nodes.Plane116.material}
        position={[-0.06, 1.43, -1.67]}
        rotation={[1.58, -0.02, -1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane117.geometry}
        material={nodes.Plane117.material}
        position={[-0.05, 1.95, -1.46]}
        rotation={[1.58, -0.02, -1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane118.geometry}
        material={nodes.Plane118.material}
        position={[-0.22, 2.66, -1.83]}
        rotation={[1.55, -0.01, -3.12]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane119.geometry}
        material={nodes.Plane119.material}
        position={[-0.34, 2.53, -1.83]}
        rotation={[1.55, -0.01, -3.12]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane120.geometry}
        material={nodes.Plane120.material}
        position={[-0.23, 2.4, -1.83]}
        rotation={[1.57, -0.01, -3.13]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane121.geometry}
        material={nodes.Plane121.material}
        position={[-0.45, 1.49, -1.82]}
        rotation={[1.55, -0.01, Math.PI]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane122.geometry}
        material={nodes.Plane122.material}
        position={[-0.31, 1.37, -1.82]}
        rotation={[1.55, -0.01, Math.PI]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane123.geometry}
        material={nodes.Plane123.material}
        position={[-0.43, 1.25, -1.81]}
        rotation={[1.55, -0.01, Math.PI]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane124.geometry}
        material={nodes.Plane124.material}
        position={[-0.23, 1.5, -1.82]}
        rotation={[1.55, -0.01, Math.PI]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane125.geometry}
        material={nodes.Plane125.material}
        position={[-0.35, 1.62, -1.82]}
        rotation={[1.55, -0.01, Math.PI]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane127.geometry}
        material={nodes.Plane127.material}
        position={[-0.38, 1.91, -1.83]}
        rotation={[1.55, -0.01, Math.PI]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane128.geometry}
        material={nodes.Plane128.material}
        position={[-0.29, 2.04, -1.83]}
        rotation={[1.57, -0.01, -3.13]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane129.geometry}
        material={nodes.Plane129.material}
        position={[-0.45, 2.17, -1.83]}
        rotation={[1.57, -0.01, -3.13]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane126.geometry}
        material={nodes.Plane126.material}
        position={[-0.61, 1.24, -1.41]}
        rotation={[1.56, 0.02, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane131.geometry}
        material={nodes.Plane131.material}
        position={[-0.61, 1.36, -1.55]}
        rotation={[1.56, 0.02, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane132.geometry}
        material={nodes.Plane132.material}
        position={[-0.62, 1.48, -1.41]}
        rotation={[1.56, 0.02, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane130.geometry}
        material={nodes.Plane130.material}
        position={[-0.64, 2.49, -1.52]}
        rotation={[1.56, 0.02, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane133.geometry}
        material={nodes.Plane133.material}
        position={[-0.64, 2.62, -1.65]}
        rotation={[1.56, 0.01, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane134.geometry}
        material={nodes.Plane134.material}
        position={[-0.64, 2.75, -1.52]}
        rotation={[1.56, 0.01, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane135.geometry}
        material={nodes.Plane135.material}
        position={[-0.64, 2.62, -1.41]}
        rotation={[1.56, 0.01, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane136.geometry}
        material={nodes.Plane136.material}
        position={[-0.63, 2, -1.53]}
        rotation={[1.56, 0.02, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane137.geometry}
        material={nodes.Plane137.material}
        position={[-0.63, 2.13, -1.66]}
        rotation={[1.56, 0.02, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane138.geometry}
        material={nodes.Plane138.material}
        position={[-0.63, 2.12, -1.41]}
        rotation={[1.56, 0.02, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane139.geometry}
        material={nodes.Plane139.material}
        position={[-0.62, 1.87, -1.61]}
        rotation={[1.56, 0.02, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane140.geometry}
        material={nodes.Plane140.material}
        position={[-0.62, 1.73, -1.48]}
        rotation={[1.56, 0.02, 1.57]}
        scale={[0.31, 0.31, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere009.geometry}
        material={nodes.Sphere009.material}
        position={[2.58, 1.02, 2.89]}
        rotation={[0.36, -0.02, -0.35]}
        scale={[0.32, 0.24, 0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere010.geometry}
        material={nodes.Sphere010.material}
        position={[2.69, 0.94, 1.74]}
        rotation={[-0.3, 0.04, -0.12]}
        scale={[0.49, 0.36, 0.49]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere011.geometry}
        material={nodes.Sphere011.material}
        position={[2.17, 1.08, 1.08]}
        rotation={[0.15, 0, 0.35]}
        scale={[0.55, 0.4, 0.55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere012.geometry}
        material={nodes.Sphere012.material}
        position={[2.03, 0.97, 0.25]}
        rotation={[0.2, 0, 0.25]}
        scale={[0.34, 0.25, 0.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere013.geometry}
        material={nodes.Sphere013.material}
        position={[2.75, 1.03, 0.21]}
        rotation={[-0.42, 0.1, -0.22]}
        scale={[0.59, 0.43, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere014.geometry}
        material={nodes.Sphere014.material}
        position={[3.3, 0.83, -0.2]}
        rotation={[-0.16, 0.04, -0.38]}
        scale={[0.35, 0.26, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere015.geometry}
        material={nodes.Sphere015.material}
        position={[3.59, 0.75, -0.67]}
        rotation={[0.18, -0.01, -0.04]}
        scale={[0.32, 0.24, 0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere016.geometry}
        material={nodes.Sphere016.material}
        position={[3.09, 0.96, 1.07]}
        rotation={[0.28, -0.07, -0.24]}
        scale={[0.52, 0.38, 0.52]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[2.77, 1.26, 1.39]}
        rotation={[0.13, -0.15, -0.35]}
        scale={[0.29, 0.22, 0.29]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[2.78, 1.42, 0.82]}
        rotation={[0.12, -0.16, -0.41]}
        scale={[0.27, 0.2, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[2.78, 0.98, 2.51]}
        rotation={[-0.38, 0.52, -0.49]}
        scale={[0.27, 0.2, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0.6, 1.32, 0.77]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane141.geometry}
        material={nodes.Plane141.material}
        position={[0.61, 1.24, 0.77]}
        scale={[0.35, 0.35, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane142.geometry}
        material={nodes.Plane142.material}
        position={[0.69, 1.15, 0.82]}
        scale={[0.35, 0.35, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane144.geometry}
        material={nodes.Plane144.material}
        position={[2.13, 1.16, -1.76]}
        rotation={[0, 0.65, 0]}
        scale={[0.35, 0.35, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane145.geometry}
        material={nodes.Plane145.material}
        position={[2.27, 1.04, -1.77]}
        rotation={[0, 0.65, 0]}
        scale={[0.35, 0.35, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane146.geometry}
        material={nodes.Plane146.material}
        position={[2.42, 0.93, -1.78]}
        rotation={[0, 0.65, 0]}
        scale={[0.35, 0.35, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane143.geometry}
        material={nodes.Plane143.material}
        position={[2.58, 0.8, -1.79]}
        rotation={[0, 0.65, 0]}
        scale={[0.35, 0.35, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane147.geometry}
        material={nodes.Plane147.material}
        position={[2.7, 0.7, -1.8]}
        rotation={[0, 0.65, 0]}
        scale={[0.35, 0.35, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[2.12, 1.28, -1.75]}
        rotation={[0, 0.65, 0]}
      />
    </group>
  )
}

useGLTF.preload(dioramaGlb)

export default Diorama